# Generated by Django 4.0.3 on 2022-03-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='cat',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_image',
            new_name='pro_image',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='selling_price',
            field=models.CharField(default='', max_length=20),
        ),
    ]
