# Generated by Django 4.0.3 on 2022-03-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_rename_title_category_cat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='selling_price',
            field=models.PositiveIntegerField(),
        ),
    ]
