# Generated by Django 4.0.3 on 2022-03-07 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_alter_category_selling_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='selling_price',
        ),
    ]
