# Generated by Django 4.0 on 2022-04-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_rename_name_cart_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user_name',
        ),
        migrations.AddField(
            model_name='cart',
            name='login_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
