# Generated by Django 4.0 on 2022-05-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0007_cart_product_quantity_alter_category_pro_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Total',
            field=models.IntegerField(default=0),
        ),
    ]
